//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EightElements.Showtime.CMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionTracking
    {
        public int Id { get; set; }
        public string RefererUrl { get; set; }
        public string RequestUrl { get; set; }
        public Nullable<int> UserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Remarks { get; set; }
        public int TrackingType { get; set; }
        public string TrafficSource { get; set; }
        public string Campaign { get; set; }
        public string PubId { get; set; }
        public string LandingPage { get; set; }
        public Nullable<int> GeolocationId { get; set; }
        public Nullable<int> TrackingCookieId { get; set; }
    }
}
