//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EightElements.Showtime.CMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentDetail
    {
        public int Id { get; set; }
        public int ContentId { get; set; }
        public string ContentSource { get; set; }
        public string ContentPath { get; set; }
        public int ContentTypeId { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
