//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EightElements.Showtime.CMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> Status { get; set; }
        public bool IsCP { get; set; }
        public Nullable<int> ContentCategoryId { get; set; }
        public Nullable<int> ContentClassificationId { get; set; }
        public Nullable<int> ContentAgeRatingId { get; set; }
    }
}
