//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EightElements.Showtime.CMS.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ShowtimeEntities : DbContext
    {
        public ShowtimeEntities()
            : base("name=ShowtimeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserDetail> UserDetails { get; set; }
        public virtual DbSet<PromotionHistory> PromotionHistories { get; set; }
        public virtual DbSet<ActionTracking> ActionTrackings { get; set; }
        public virtual DbSet<Content> Contents { get; set; }
        public virtual DbSet<ContentFeedback> ContentFeedbacks { get; set; }
        public virtual DbSet<ContentItem> ContentItems { get; set; }
        public virtual DbSet<ContentRating> ContentRatings { get; set; }
        public virtual DbSet<ContentTransaction> ContentTransactions { get; set; }
        public virtual DbSet<ContentType> ContentTypes { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventCategory> EventCategories { get; set; }
        public virtual DbSet<EventDetail> EventDetails { get; set; }
        public virtual DbSet<EventEliminate> EventEliminates { get; set; }
        public virtual DbSet<EventParticipant> EventParticipants { get; set; }
        public virtual DbSet<EventVote> EventVotes { get; set; }
        public virtual DbSet<Geolocation> Geolocations { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Log_Sandbox> Log_Sandbox { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<PageText> PageTexts { get; set; }
        public virtual DbSet<PortalConfig> PortalConfigs { get; set; }
        public virtual DbSet<PostbackTracking> PostbackTrackings { get; set; }
        public virtual DbSet<Promotion> Promotions { get; set; }
        public virtual DbSet<RedirectTracking> RedirectTrackings { get; set; }
        public virtual DbSet<SpaceTime> SpaceTimes { get; set; }
        public virtual DbSet<SubscriptionPrice> SubscriptionPrices { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TrackingCookie> TrackingCookies { get; set; }
        public virtual DbSet<TrackingExtension> TrackingExtensions { get; set; }
        public virtual DbSet<TransactionCallback> TransactionCallbacks { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Subscription> Subscriptions { get; set; }
        public virtual DbSet<UserAdmin> UserAdmins { get; set; }
        public virtual DbSet<ContentAgeRating> ContentAgeRatings { get; set; }
        public virtual DbSet<ContentCategory> ContentCategories { get; set; }
        public virtual DbSet<ContentCategoryPlatformMap> ContentCategoryPlatformMaps { get; set; }
        public virtual DbSet<ContentClassification> ContentClassifications { get; set; }
        public virtual DbSet<ContentPlatform> ContentPlatforms { get; set; }
        public virtual DbSet<ContentTag> ContentTags { get; set; }
    
        public virtual ObjectResult<ReportNewuser_Result> ReportNewuser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ReportNewuser_Result>("ReportNewuser");
        }
    }
}
