//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EightElements.Showtime.CMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventEliminate
    {
        public int Id { get; set; }
        public Nullable<int> EventId { get; set; }
        public Nullable<int> EventParticipantId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> EliminationDate { get; set; }
        public Nullable<bool> Exception { get; set; }
    }
}
