//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EightElements.Showtime.CMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public long Id { get; set; }
        public string NewsType { get; set; }
        public string LanguageCode { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string ShortDescription { get; set; }
        public string WebThumbnail { get; set; }
        public string MobileThumbnail { get; set; }
        public string ContentTemplate { get; set; }
        public System.DateTime PublishedDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime ExpiredDate { get; set; }
        public string RelatedNews { get; set; }
        public bool IsPublished { get; set; }
        public bool IsActive { get; set; }
        public string PublishedBy { get; set; }
        public string BlockType { get; set; }
        public string VideoUrl { get; set; }
        public string BlockContentType { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ProjectCode { get; set; }
    }
}
