//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EightElements.Showtime.CMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string RealName { get; set; }
        public string StageName { get; set; }
        public string PhoneNumber { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public byte Status { get; set; }
    }
}
