//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EightElements.Showtime.CMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostbackTracking
    {
        public int Id { get; set; }
        public Nullable<int> ActionTrackingId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string RequestLink { get; set; }
        public string Partner { get; set; }
        public int StatusId { get; set; }
        public string StatusDescription { get; set; }
        public double Payout { get; set; }
    }
}
