//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EightElements.Showtime.CMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RedirectTracking
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ActionTrackingId { get; set; }
        public string Reference { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string Result { get; set; }
        public Nullable<int> Flag { get; set; }
        public string Remarks { get; set; }
        public string RedirectUrl { get; set; }
        public string GuestInfo { get; set; }
    }
}
