//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EightElements.Showtime.CMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackingExtension
    {
        public int Id { get; set; }
        public Nullable<int> ActionTrackingId { get; set; }
        public string Category { get; set; }
        public string Action { get; set; }
        public string Label { get; set; }
        public string value { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string TrackingType { get; set; }
    }
}
