//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EightElements.Showtime.CMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionCallback
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Status { get; set; }
        public string CallbackData { get; set; }
        public Nullable<int> TransactionId { get; set; }
        public string PaymentTransactionId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
