//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EightElements.Showtime.CMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Provider { get; set; }
        public string LoginId { get; set; }
        public string UserbaseId { get; set; }
        public string Email { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string C_ExternalLoginId { get; set; }
        public string C_DisplayName { get; set; }
        public string C_Image { get; set; }
        public string ProfileName { get; set; }
    }
}
