use [8ePing]

--noted
--ActionTracking -> redirectTracking (id send to payment or telco )
--subcription(ceck subcription user,MSiSDN update no numbers phone or uid,TrafficSource from table actionTracking->Traficsource)
--http://pk.gamerheaven.8elements.mobi/subscribe?utm_source=Xtraffic&utm_campaign=Chttp://pk.gamerheaven.8elements.mobi:80/subscribe/subscribe?utm_source=Xtraffic&utm_campaign=CPA_0.05_EN&lp=zombiechase3&payout=0.05&pub_id=5997&click_id=5sqhudxmj3zi1u1uityo0ow00,16069611,5,5997A_0.05_EN&lp=zombiechase3&payout=0.05&pub_id=5997&click_id=5sqhudxmj3zi1u1uityo0ow00,16069611,5,5997
--this is the program code
Select top 2 * from [dbo].[ActionTracking] with (nolock)
Select top 2 * from [dbo].[redirectTracking] with (nolock)
Select top 2 * from [dbo].[subscription] with(nolock)
-------------------------

select top 2 * from [dbo].[AccessToken] with (nolock)
select top 20 * from [dbo].[ActionTracking] with (nolock) 
where TrafficSource is not null
order by id desc
http://pk.gamerheaven.8elements.mobi:80/subscribe/subscribe?utm_source=Xtraffic&utm_campaign=CPA_0.05_EN&lp=zombiechase3&payout=0.05&pub_id=5997&click_id=5sqhudxmj3zi1u1uityo0ow00,16069611,5,5997
select top 2 * from [dbo].[ActionTrackingFraud] with (nolock)
select top 2 * from [dbo].[ActionTrackingtype] with (nolock)
Select top 2 * from [dbo].[activityLog] with (nolock)
select top 2 * from [dbo].[ApplicationMenu] with(nolock)
select top 2 * from [dbo].[ApprovalHistory] with(nolock)
select top 2 * from [dbo].[Author] with(nolock)
select top 2 * from [dbo].[BlackList] with(nolock)
Select top 2 * from [dbo].[BlockedMsisdn] with (nolock)
select top 2 * from [dbo].[Brand] with (nolock)
Select top 2 * from [dbo].[catalog] with (nolock)
select top 2 * from [dbo].[catalogGame] with (nolock)
select top 2 * from [dbo].[CdrHistory] with(nolock)
select top 2 * from [dbo].[ChargingApiconfigurations] with(nolock)
select top 2 * from [dbo].[cmsUser] with (nolock)
select top 2 * from [dbo].[comboboxSetting] with (nolock)
select top 2 * from [dbo].[Content] with (nolock)
Select top 2 * from [dbo].[Content_20190213] with(nolock)
select top 2 * from [dbo].[Content_bak20190911] with(nolock)
select top 2 * from [dbo].[ContentExtension] with(nolock)
select top 2 * from [dbo].[ContentFiles] with (nolock)
select top 2 * from [dbo].[ContentFilesUpdateConfigurations] with(nolock)
select top 2 * from [dbo].[ContentFilesVersions] with (nolock)
select top 2 * from [dbo].[ContentGame] with (nolock)
select top 2 * from [dbo].[contentGameCategory] with (nolock)
select top 2 * from [dbo].[contentGameCntGameLangs] with (nolock)
select top 2 * from [dbo].[ContentGameControls] with (nolock)
select top 2 * from [dbo].[ContentGameCopyright] with (nolock)
select top 2 * from [dbo].[ContentGameDistributionRights] with(nolock)
select top 2 * from [dbo].[ContentGameFeature] with(nolock)
Select top 2 * from [dbo].[ContentGameHtp] with(nolock)
select top 2 * from [dbo].[ContentGameLanguages] with(nolock)
Select Top 2 * from [dbo].[ContentGameLongDspt] with (nolock)
select top 2 * from [dbo].[contentGameName] with(nolock)
select top 3 * from [dbo].[ContentGamePlatformSupport] with (nolock)
Select top 2 * from [dbo].[ContentGameShortDspt] with (nolock)
Select top 2 * from [dbo].[contentGameWap] with (nolock)
select top 2 * from [dbo].[ContentGroup] with (nolock)
Select top 2 * from [dbo].[ContentImages] with(nolock)
select top 2 * from [dbo].[ContentLanguage] with (nolock)
select top 2 * from [dbo].[ContentListPriority] with (nolock)
select top 2 * from [dbo].[ContentListPriority_bak20180228] with(nolock)
select top 2 * from [dbo].[ContentRedirectToUrl] with (nolock)
Select top 2 * from [dbo].[ContentTexts] with(nolock)
select top 2 * from [dbo].[ContentUsage] with (nolock)
select top 2 * from [dbo].[ContentVideo] with (nolock)
Select top 2 * from [dbo].[ContentVideoCategory] with(nolock)
select top 2 * from [dbo].[ContentWallPap] with (nolock)
select top 2 * from [dbo].[ContentWallpapCopyright] with (nolock)
select top 2 * from [dbo].[ContentWallpapDspt] with(nolock)
select top 2 * from [dbo].[ContentWallpapName] with (nolock)
Select top 2 * from [dbo].[ConversionPostback] with(nolock)
Select top 2 * from [dbo].[Country] with(nolock)
Select top 2 * from [dbo].[CPReport] with(nolock)
Select top 2 * from [dbo].[CPReportToSale] with(nolock)
Select top 2 * from [dbo].[Currency] with(nolock)
Select top 2 * from [dbo].[CurrencyExhgRate] with(nolock)
Select top 2 * from [dbo].[Customer] with(nolock)
Select top 2 * from [dbo].[DataChgLog] with (nolock)
Select top 2 * from [dbo].[Downloads] with(nolock)
Select top 2 * from [dbo].[DownloadUrlRequest] with(nolock)
Select top 2 * from [dbo].[DrmTracking] with(nolock)
Select top 2 * from [dbo].[DsptLang] with (nolock)
Select top 2 * from [dbo].[EventTracking] with(nolock)
Select top 2 * from [dbo].[FraudTracking] with(nolock)
Select top 2 * from [dbo].[GameBundle] with(nolock)
Select top 2 * from [dbo].[GameBundleContents] with(nolock)
Select top 2 * from [dbo].[GameBundleDownloads] with(nolock)
Select top 2 * from [dbo].[GameBundleList] with(nolock)
Select top 2 * from [dbo].[GameBundlePrice] with(nolock)
Select top 2 * from [dbo].[GameBundleTexts] with(nolock)
Select top 2 * from [dbo].[GameBundleTransactions] with(nolock)
Select top 2 * from [dbo].[GameCategory] with(nolock)
Select top 2 * from [dbo].[GameCategoryImages] with(nolock)
Select top 2 * from [dbo].[GameCategoryLongDspt] with(nolock)
Select top 2 * from [dbo].[GameCategoryShortDspt] with(nolock)
Select top 2 * from [dbo].[GameCategoryTexts] with(nolock)
Select top 2 * from [dbo].[GameFileType] with(nolock)
Select top 2 * from [dbo].[groupApproval] with(nolock)
Select top 2 * from [dbo].[Handset] with(nolock)
Select top 2 * from [dbo].[HandsetBackFillLog] with (nolock)
Select top 2 * from [dbo].[HandsetBrand] with(nolock)
select top 2 * from [dbo].[HandsetGmeCtntMap] with(nolock)