//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoresWebAPI_Web_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int sale_id { get; set; }
        public string store_id { get; set; }
        public string order_num { get; set; }
        public System.DateTime order_date { get; set; }
        public short quantity { get; set; }
        public string pay_terms { get; set; }
        public int book_id { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Store Store { get; set; }
    }
}
