//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoresWebAPI_Web_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string user_id { get; set; }
        public string password { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public short job_id { get; set; }
        public Nullable<byte> job_level { get; set; }
        public int pub_id { get; set; }
        public System.DateTime hire_date { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual Publisher Publisher { get; set; }
    }
}
